### ISSUE TITLE
This repo looks abandoned. 

### ISSUE THREAD

**Issue by ryan-hamblin** [beerjs/saltlakecity#1]
I would like to take over it's responsibilities.

**Comment by jordanpapaleo** [comment]
I’ll add you tonight as no one replied

**Comment by ryan-hamblin** [comment]
Awesome!

**Comment by jordanpapaleo** [comment]
You should be good

**Comment by tylerdmace** [comment]
Sorry! Got busy with work and didn't see this stuff until too late. I've since moved to NYC and am not the best person any longer (was I ever?).
